events collector

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,6 +52,6 @@ jobs:
       - name: Copy utils.py
         run: 'for d in */; do cp utils.py "$d"; done'
       - name: build
-        run: sam build  --template cfn-template.yml  && sam package --s3-bucket pbr-lambda-packages --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --output-template-file cfn-packaged.yaml --region us-east-1 || { echo 'my_command failed' ; exit 1; }
+        run: sam build  --template cfn-template.yml  && sam package --s3-bucket my-bucket --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --output-template-file cfn-packaged.yaml --region us-east-1 || { echo 'my_command failed' ; exit 1; }
       - name: deploy
-        run: sam deploy --template-file cfn-packaged.yaml --s3-bucket pbr-lambda-packages --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --stack-name "${{steps.setrepo.outputs.repo_name}}-${{steps.setenv.outputs.env_name}}-stack" --capabilities CAPABILITY_NAMED_IAM --region us-east-1 --role-arn ${{env.CLOUD_FORMATION_ROLE}} --no-fail-on-empty-changeset --parameter-overrides Environment=${{steps.setenv.outputs.env_name}} || { echo 'my_command failed' ; exit 1; }
+        run: sam deploy --template-file cfn-packaged.yaml --s3-bucket my-bucket --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --stack-name "${{steps.setrepo.outputs.repo_name}}-${{steps.setenv.outputs.env_name}}-stack" --capabilities CAPABILITY_NAMED_IAM --region us-east-1 --role-arn ${{env.CLOUD_FORMATION_ROLE}} --no-fail-on-empty-changeset --parameter-overrides Environment=${{steps.setenv.outputs.env_name}} || { echo 'my_command failed' ; exit 1; }
