Update workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -99,8 +99,8 @@ jobs:
           aws-region: us-east-1
           # role-to-assume: arn:aws:iam::807324965916:role/cdk-hnb659fds-deploy-role-807324965916-us-east-1
           role-duration-seconds: 900
-      # - name: Install sam cli
-      #   run: 'pip3 install aws-sam-cli'
+      - name: Install sam cli
+        run: 'pip3 install aws-sam-cli'
       - name: Complete policies
         run: |
           aws iam attach-user-policy \
@@ -118,4 +118,4 @@ jobs:
         # run: aws cloudformation package --template-file template.yml --s3-bucket mother-blooding-bucket --output-template-file packaged.yaml
         run: sam build && sam package --s3-bucket mother-blooding-bucket --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --output-template-file packaged.yaml --region us-east-1 || { echo 'my_command failed' ; exit 1; }
       - name: deploy
-        run: sam deploy --template-file packaged.yaml --s3-bucket mother-blooding-bucket --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --stack-name "${{steps.setrepo.outputs.repo_name}}-${{steps.setenv.outputs.env_name}}-stack" --capabilities "CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND" --region us-east-1 --no-fail-on-empty-changeset --parameter-overrides Environment=${{steps.setenv.outputs.env_name}} || { echo 'my_command failed' ; exit 1; }
+        run: sam deploy --template-file packaged.yaml --s3-bucket mother-blooding-bucket --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --stack-name "${{steps.setrepo.outputs.repo_name}}-${{steps.setenv.outputs.env_name}}-stack" --capabilities CAPABILITY_NAMED_IAM --capabilities CAPABILITY_AUTO_EXPAND --region us-east-1 --no-fail-on-empty-changeset --parameter-overrides Environment=${{steps.setenv.outputs.env_name}} || { echo 'my_command failed' ; exit 1; }
