back to norm

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -101,10 +101,21 @@ jobs:
           role-duration-seconds: 900
       # - name: Install sam cli
       #   run: 'pip3 install aws-sam-cli'
+      - name: Complete policies
+        run: |
+          aws iam attach-user-policy \
+          --policy-arn arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess \
+          --policy-arn arn:aws:iam::aws:policy/CloudWatchEventsFullAccess \
+          --policy-arn arn:aws:iam::aws:policy/AWSLambda_FullAccess \
+          --policy-arn arn:aws:iam::aws:policy/IAMFullAccess \
+          --policy-arn arn:aws:iam::aws:policy/AWSCloudFormationFullAccess \
+          --policy-arn arn:aws:iam::aws:policy/AmazonSQSFullAccess \
+          --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess \
+          --user-name Memphis
       - name: Copy utils.py
         run: 'for d in */; do cp utils.py "$d"; done'
       - name: build
-        run: aws cloudformation package --template-file template.yml --s3-bucket mother-blooding-bucket --output-template-file packaged.yaml
-        # run: sam build && sam package --s3-bucket mother-blooding-bucket --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --output-template-file cfn-packaged.yaml --region us-east-1 || { echo 'my_command failed' ; exit 1; }
+        # run: aws cloudformation package --template-file template.yml --s3-bucket mother-blooding-bucket --output-template-file packaged.yaml
+        run: sam build && sam package --s3-bucket mother-blooding-bucket --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --output-template-file packaged.yaml --region us-east-1 || { echo 'my_command failed' ; exit 1; }
       - name: deploy
-        run: aws cloudformation deploy --template-file packaged.yaml --s3-bucket mother-blooding-bucket --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --stack-name "${{steps.setrepo.outputs.repo_name}}-${{steps.setenv.outputs.env_name}}-stack" --capabilities CAPABILITY_NAMED_IAM --region us-east-1 --no-fail-on-empty-changeset --parameter-overrides Environment=${{steps.setenv.outputs.env_name}} || { echo 'my_command failed' ; exit 1; }
+        run: sam deploy --template-file packaged.yaml --s3-bucket mother-blooding-bucket --s3-prefix "${{steps.setrepo.outputs.repo_name}}/${{steps.setbranch.outputs.branch_name}}/${{steps.setenv.outputs.env_name}}" --stack-name "${{steps.setrepo.outputs.repo_name}}-${{steps.setenv.outputs.env_name}}-stack" --capabilities CAPABILITY_NAMED_IAM --region us-east-1 --no-fail-on-empty-changeset --parameter-overrides Environment=${{steps.setenv.outputs.env_name}} || { echo 'my_command failed' ; exit 1; }
